project: BR-training
group: BR
name: br
width: 64
depth: 3
tuning_set: data/adroit_pen/adroit_pen_tuning_set.hdf5
mapper_num_iters: 1000
n_data: 512
wasserstein_steps_0: 0
wasserstein_steps_1: 1200
n_samples: 1024
wasserstein_lr: 0.001
lr: 0.08
save_ckpt_every: 50
print_every: 20
batch_size: 256
num_samples: 40
n_discarded: 10
num_burn_in_steps: 2000
keep_every: 2000
sghmc_lr: 0.01
num_chains: 4
mdecay: 0.01
print_every_n_samples: 5
dataset: data/adroit_pen/AdroitHandPen-v1_pref_b.hdf5
training_split: 0.8
run_prior_tuning: true
run_training: true
seed: 1
OUT_DIR: ./exp/reward_learning/pen